services:
  sishi_bufet.controller.sushi:
    class: Sushi\SushiBufetBundle\Controller\Main\SushiController
    arguments:
        - '@sushi_bufet.service.dish'
    calls:
      - [ setContainer, [ '@service_container' ]]