<?php

namespace Sushi\SushiBufetBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishRepository extends BaseRepository
{

}
